apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
  labels:
    app: kafka-neo4j-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
        - name: kafka-connect
          image: veedata/kafka-neo4j-connect:latest
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/etc/kafka-connect/jars"
          ports:
            - name: rest
              containerPort: 8083
          volumeMounts:
            - name: connector-plugins
              mountPath: /etc/kafka-connect/jars
      volumes:
        - name: connector-plugins
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connector
spec:
  selector:
    app: kafka-neo4j-connector
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
  type: ClusterIP